# Generated by Django 3.1.1 on 2020-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphe',
            name='Titre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
